config/routes.rb
Rails.application.routes.draw do
  resources :cards
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
   validates :card_id, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    if params[:keyword]
      @key = params[:keyword];
      @cards = Card.where("name LIKE '%"+ @key + "%' or card_id LIKE '%"+ @key + "%' or note LIKE '%" + @key + "%'").order('card_id')
    else
      @cards = Card.all.order('card_id')
    end
     @card = Card.new # 新規作成用
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to cards_path, notice: 'Card was successfully created.' }
        format.json { render @card, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to cards_path, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:name, :card_id, :note)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.erb
<center>
    <%= form_with(model: card, local: true) do |form| %>
        <% if card.errors.any? %>
            <div id="error_explanation">
                <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

                <ul>
                    <% card.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>

        <div class="field">
            <%= form.label 'カード番号*' %>
            <%= form.text_field :card_id, id: :card_card_id %>
        </div>
        <div class="field">
            <%= form.label 'カード名' %>
            <%= form.text_field :name, id: :card_name %>
        </div>
        <div class="field">
            <%= form.label 'コメント' %>
            <%= form.text_field :note, id: :card_note %>
        </div>

        <div class="actions">
            <%= form.submit %>
        </div>
    <% end %>
</center>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>

<center>
    <%= form_tag cards_path, method: 'get' do %>
        <p>
            <%= text_field_tag :keyword, @key %>
            <%= submit_tag "検索"%>
        </p>
    <% end %>
</center>

<table border align="center" style="table-layout:fixed;">
    <caption>
        <font size="5"><strong>所持カード一覧</strong></font>
        <font size="3"><strong>所持枚数 <%= @cards.size %> 枚</strong></font>
        <button type="button" class="btn btn-primary pull-right" data-toggle="modal" data-target="#modal-register">新規登録</button>
    </caption>
    <thead>
        <tr>
            <th width="35%">カード番号</th>
            <th width="35%">カード名</th>
            <th width="20%">コメント</th>
            <th width="5%">編集</th>
            <th width="5%">削除</th>
        </tr>
    </thead>
    <tbody>
        <% @cards.each do |card| %>
            <tr>
                <td><%= card.card_id %></td>
                <td><%= card.name %></td>
                <td><%= card.note %></td>
                <td><%= link_to '編集', edit_card_path(card), class: "btn btn-default" %></td>
                <td><%= link_to '削除', card, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<!-- モーダルの配置 -->
<div class="modal fade" id="modal-register" tabindex="-1">
    <div class="modal-dialog modal-sm">
        <%= form_for @card do |f| %>
            <!-- モーダルのコンテンツ -->
            <div class="modal-content">
                <!-- モーダルのヘッダ -->
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="modal-label">新規カード登録</h4>
                </div>
                <!-- モーダルのボディ -->
                <div class="modal-body">
                    <%= f.label "カード番号*" %>
                    <%= f.text_field :card_id %>
                    <%= f.label "カード名" %>
                    <%= f.text_field :name %>
                    <%= f.label "コメント" %>
                    <%= f.text_field :note %>
                </div>
                <!-- モーダルのフッタ -->
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
                    <%= f.submit "新規追加", class: "btn btn-primary"%>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @card.name %>
</p>

<p>
  <strong>Card:</strong>
  <%= @card.card_id %>
</p>

<p>
    <strong>Note:</strong>
    <%= @card.note %>
</p>


<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>カード管理アプリ</title>
    <%= csrf_meta_tags %>

    <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script crossorigin="anonymous" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
        <div class="navbar-header">
            <ul class="nav navbar-nav">
                <li><%= link_to '所持カード一覧', cards_path %></li>
            </ul>
        </div>
    </nav>
    <%= yield %>
  </body>
</html>